apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: tonisgarden-statestore
  namespace: {{ .Values.namespace }}
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis:6379
  - name: redisPassword
    secretKeyRef:
      name: tonisgarden-secrets
      key: RedisPassword
  - name: actorStateStore
    value: "true"
