apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: tonisgarden-secretstore
  namespace: {{ .Values.namespace }}
spec:
  type: secretstores.kubernetes
  version: v1
  metadata:
  - name: ""